### ISSUE TITLE
ctrlX-DataLayer Nuget package does not exist

### ISSUE THREAD

**Issue by ArcherThompson** [boschrexroth/ctrlx-automation-sdk#28]
Using command `dotnet add package ctrlX-DataLayer --version 3.0.3` nor searching on nuget, [https://www.nuget.org/packages?q=ctrlX-DataLayer] finds a package.

additionally a version-less search yields the same issue:
`dotnet add package ctrlX-DataLayer`
```
Determining projects to restore...
Writing /tmp/tmpTZyZL0.tmp
info : X.509 certificate chain validation will use the fallback certificate bundle at  '/usr/share/dotnet/sdk/7.0.203/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at  '/usr/share/dotnet/sdk/7.0.203/trustedroots/timestampctl.pem'.
info : Adding PackageReference for package 'ctrlX-DataLayer' into project '<my_path>'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/ctrlx-datalayer/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/ctrlx-datalayer/index.json 195ms
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/ctrlx-datalayer/index.json
info :   NotFound https://api.nuget.org/v3/registration5-gz-semver2/ctrlx-datalayer/index.json 245ms
error: There are no versions available for the package 'ctrlX-DataLayer'.```

**Comment by ArcherThompson** [comment]
This is not clearly dicussed in any documentation I could find but the package is available via:

`dotnet nuget add source https://nuget.pkg.github.com/boschrexroth/index.json -n GITHUB -u YOUR_GITHUB_USERNAME -p YOUR_PERSONAL_ACCESS_TOKEN --store-password-in-clear-text`

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Because of security reasons we decided not to publish the ctrlX-Datalayer and ctrlx-Datalayer-Flatbuffers NuGet package on NuGet.org, instead please unpack from official ctrlX [Releases ](https://github.com/boschrexroth/ctrlx-automation-sdk/releases/ ) or fetch from github packages

https://github.com/boschrexroth/ctrlx-automation-sdk/pkgs/nuget/ctrlX-DataLayer
https://github.com/boschrexroth/ctrlx-automation-sdk/pkgs/nuget/ctrlX-DataLayer

by adding this to you NuGet source. Please see the How To in attachment
[NuGet packages from github.pdf](https://github.com/boschrexroth/ctrlx-automation-sdk/files/14526273/NuGet.packages.from.github.pdf)
