### ISSUE TITLE
npm install not working on node sample data layer provider

### ISSUE THREAD

**Issue by gmantoha** [boschrexroth/ctrlx-automation-sdk#39]
I ran the two scripts `install-required-packages.sh` with tag 2.4.3 and `clone-install-sdk.sh`.
After that tried to install npm packages but got the error:

```
~/projects/ctrlx-automation-sdk/samples-node/datalayer.provider.simple$ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ctrlx-datalayer-flatbuffers@^2.6.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I it should install all npm packages so that I can build the snap package.

**Comment by gmantoha** [comment]
It seems that ctrlx-datalayer is dependend on ctrlx-datalayer-flatbuffers Version 2.6.0 see here:
https://www.npmjs.com/package/ctrlx-datalayer?activeTab=code
```
"dependencies": {
        "ctrlx-datalayer-flatbuffers": "^2.6.0",
        "flatbuffers": "^23.5.26",
        "node-addon-api": "^7.1.0",
        "node-gyp-build": "^4.8.0"
    },
```

But ctrlx-datalayer-flatbuffers current Version is 2.4.0 see here:
https://www.npmjs.com/package/ctrlx-datalayer-flatbuffers
```
$ npm show ctrlx-datalayer-flatbuffers
ctrlx-datalayer-flatbuffers@2.4.0 | MIT | deps: 1 | versions: 9
```

**Comment by gmantoha** [comment]
I can override the version in package.json with: ```"overrides": {
        "ctrlx-datalayer-flatbuffers": "^2.4.0"
    }```.
With that ```npm install``` works but when trying to build the snap it again tries to fetch version ```2.6.0``` of the flatbuffers package.

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Unfortunately a prerelease of the Node.js API 2.6.0 (2.2.0) has been published by accident to nodejs.org, so we revoked it: [ctrlx-datalayer - npm (npmjs.com)](https://www.npmjs.com/package/ctrlx-datalayer)

Because the SDK 2.6.0 not released yet but almost finished, please use latest official Node.js API ctrlx-datalayer 2.1.1, which consumes ctrlx-datalayer-flatbfuffers 2.4.0. If you still need a new flatbuffers type, please ask us for any preview.
